### ISSUE TITLE
"type interface error "应该是 "type error interface" 

### ISSUE THREAD

**Issue by Degfy** [bigwhite/GoProgrammingFromBeginnerToMaster#1]
type interface error {    Error() string}
格式引文：
白明著.Go语言精进之路：从新手到高手的编程思想、方法和技巧1.机械工业出版社华章分社.2022:642.
得到电子书：https://d.dedao.cn/DrTmNccjNtum4ouI

**Comment by Degfy** [comment]
![error](https://user-images.githubusercontent.com/15191087/153116742-ac8939fb-31d9-4acf-85fd-e482ff194817.jpg)

**Comment by bigwhite** [comment]
火眼金睛啊，感谢！
