### ISSUE TITLE
第一册 P62 图8-1变量类型括号错位

### ISSUE THREAD

**Issue by jackbai233** [bigwhite/GoProgrammingFromBeginnerToMaster#12]
图8-1(变量声明形式使用决策流程图) 中，在“是否使用默认类型”--> "N" 时：
1. 局部变量声明方式：书中为 `a :=(int32)17` ，实际应为 `a := int32(17)`。
2. 包级变量声明方式：书中为 `var a = (int32)17`，实际应为 `var a = int32(17)`
![image](https://user-images.githubusercontent.com/24272763/167813251-92fc3f15-0975-4c7a-a287-fff375e058f2.jpeg)

**Comment by bigwhite** [comment]
已更新到勘误表，感谢指出。
