### ISSUE TITLE
纸质第一册 P89 chapter3/sources/slice_unbind_orig_array.go代码中数组u初始化有笔误

### ISSUE THREAD

**Issue by jackbai233** [bigwhite/GoProgrammingFromBeginnerToMaster#13]
按照书中上下文与代码中的打印描述， 代码中的变量 `u`应为数组，故初始化应为：`u := [5]int{11, 12, 13, 14, 15}` 或 `u := [...]int{11, 12, 13, 14, 15}`。 书中为`u := []int{11, 12, 13, 14, 15}`
https://github.com/bigwhite/GoProgrammingFromBeginnerToMaster/blob/af651d9156af497340e6e75aadda6a9215b3942a/chapter3/sources/slice_unbind_orig_array.go#L6

**Comment by bigwhite** [comment]
感谢指出，已更新到勘误，并更新了slice_unbind_orig_array.go源码。
