### ISSUE TITLE
纸质第一册 P94 map[string]int类型变量初始化声明有误

### ISSUE THREAD

**Issue by jackbai233** [bigwhite/GoProgrammingFromBeginnerToMaster#14]
如下图： 书中之前已说明 map类型不属于 “零值可用”，因此不能直接声明创建：`m := map[string]int` ， 在不使用字面量创建的情况下，应使用 `make`内建函数创建。
![image](https://user-images.githubusercontent.com/24272763/168057269-df39c21c-409d-4c0e-8404-ed3e61e22d95.jpeg)

**Comment by bigwhite** [comment]
感谢指出，这个应该是typo，原本是要写m := map[string]int{}的(手动允悲)，已更新到勘误。
