### ISSUE TITLE
纸质第一册 P36  图中 README.md 笔误

### ISSUE THREAD

**Issue by XQ-Gang** [bigwhite/GoProgrammingFromBeginnerToMaster#15]
应将 PEADME.md 修改为 README.md，如下图所示：

![origin_img_v2_809c4b4c-04a8-4ae7-9f2c-6cd1a17c939g](https://user-images.githubusercontent.com/92232031/170872387-9e3c76ae-deca-451a-ac83-a604dad24a33.jpg)

**Comment by bigwhite** [comment]
感谢指出。该typo问题之前有读者已经提出，并在勘误表第5项中公示了。
