### ISSUE TITLE
微信阅读 14.2 chapter3/sources/map_stable_iterate.go的示例代码容易误解

### ISSUE THREAD

**Issue by bravility** [bigwhite/GoProgrammingFromBeginnerToMaster#18]
在微信读书的14.2中提到

> 如果你需要一个稳定的遍历次序，那么一个比较通用的做法是使用另一种数据结构来**按需要的次序**保存key，比如切片：

随后展示chapter3/sources/map_stable_iterate.go的示例代码：

![image](https://user-images.githubusercontent.com/6559992/172836225-6414e67b-a4cb-44cb-a21c-9c18882059f4.png)

----------
身为读者读到这里误以为了切片能解决map在range中的乱序问题，并且示例代码的输出次序刚好跟map的原始初始次序是一致的

**但！这仅仅是一个巧合而已。**

作者在这里想要表达的应该是切片可以固定第一次range map的乱序，保证在后续的range中都是这样的乱序次序，而并不是说切片可以保持顺序、逆序或者map定义时的次序。

建议修正代码使用以下例子可以避免存在误读作者意图
![image](https://user-images.githubusercontent.com/6559992/172837658-da1dcc1f-5696-4130-8801-56d535944d0a.png)

**Comment by bigwhite** [comment]
感谢指出。该问题之前已经有其他读者提出，可在勘误表第9条中查看。
