### ISSUE TITLE
第一册 P27 素数的定义 & 代码fi连字的问题

### ISSUE THREAD

**Issue by suica** [bigwhite/GoProgrammingFromBeginnerToMaster#22]
1. 素数应当描述成“有且仅有两个截然不同的自然数因数，1和它本身”。原文缺少“仅有”两个，这使得任意一个正合数都可以满足这里的定义；且在中文语境中，“除数”显得也不太精确，建议使用因数代替。

1. 代码的字体或许启用了连字，"fi"相互连接，两个字符合起来仅占用了一个字符的空间，并不是等宽的，阅读起来不够美观。这点是否可以通过关闭连字来解决？

**Comment by suica** [comment]
连字问题在P57的代码清单中，各处宽度不一致的`float`也能够体现出来。

**Comment by bigwhite** [comment]
看的真细致啊。感谢指出。
