### ISSUE TITLE
chapter6/sources/go-concurrency-pattern-5.go

### ISSUE THREAD

**Issue by osxtest** [bigwhite/GoProgrammingFromBeginnerToMaster#28]
- 通知并等待一个 goroutine 退出
  - 在代码 https://github.com/bigwhite/GoProgrammingFromBeginnerToMaster/blob/main/chapter6/sources/go-concurrency-pattern-5.go#L18 后再添加一个 `return` 是否更好理解呢？
  - 因为 `case <-quit:` 分支完成后，在 main goroutine 没结束前 for 循环还会继续，worker 可能还会再工作

```diff
func spawn(f func(int)) chan string {
	quit := make(chan string)
	go func() {
		var job chan int // 模拟job channel
		for {
			select {
			case j := <-job:
				f(j)
			case <-quit:
				quit <- "ok"
+				return
			}
		}
	}()
	return quit
}
```

**Comment by bigwhite** [comment]
这个不是好不好理解的问题，这个就是问题，就应该有一个return，当worker goroutine收到quit通知后，就应该马上退出。感谢指出问题。该问题将更新到勘误表。

**Comment by bigwhite** [comment]
这个不是好不好理解的问题，这个就是问题，就应该有一个return，当worker goroutine收到quit通知后，就应该马上退出。感谢指出问题。该问题将更新到勘误表。

**Comment by txjjjjj** [comment]
`var job chan int // 模拟job channel`  这个可以稍微多说两句吗, 或者具体化一下.  因为本质应该是来调度worker函数的
没理解这个job chan的实际意义.
