### ISSUE TITLE
第一册，第七条，7.1简单且一致下面的问题。

### ISSUE THREAD

**Issue by lesserror-hxr** [bigwhite/GoProgrammingFromBeginnerToMaster#30]
在Mac下面，进入到$GOROOT下的src目录中，执行以下命令：

cat $(find . -name '*.go') | indents | sort | uniq -c | sort -nr | sed 30q

无论是bash还是zsh，都会报错：command not found: indents

**Comment by bigwhite** [comment]
这块儿少了一个脚注：indents命令的下载安装地址：indents命令：https://github.com/bigwhite/go/tree/master/cmd/indents
