### ISSUE TITLE
Maybe "block" here?

### ISSUE THREAD

**Issue by bestgopher** [bigwhite/GoProgrammingFromBeginnerToMaster#32]
https://github.com/bigwhite/GoProgrammingFromBeginnerToMaster/blob/d3e5793e05f08835e32ec669cc7f749888e6f20f/chapter8/sources/pprof_standalone1.go#L69

**Comment by bigwhite** [comment]
Could you give us more detail about why this line maybe block?

**Comment by bestgopher** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/36840497/202997346-f8b58b4b-ae74-4a9b-a7e9-4ed99cb5ebc7.png">
@bigwhite

**Comment by bigwhite** [comment]
Got it! I have fixed it in source code and add an entry to the errata.md.
