### ISSUE TITLE
项目怎么运行的?

### ISSUE THREAD

**Issue by a982246809** [bigwhite/GoProgrammingFromBeginnerToMaster#36]

**Comment by bigwhite** [comment]
项目是书籍的代码例子，每个例子都可以单独运行。

**Comment by sakurafly123** [comment]
> 项目是书籍的代码例子，每个例子都可以单独运行。

怎么单独运行，能不能写到ReadeME 里面，我现在1.6 版本，执行 chapter3.item16-demo/chapter3-demo1时，go install 会报go install github.com/bigwhite/effective-go-book/chapter3-demo1/
pkg/pkg1
go install: version is required when current directory is not in a module       
        Try 'go install github.com/bigwhite/effective-go-book/chapter3-demo1/pkg
/pkg1@latest' to install the latest version，继续按照报错执行会报fatal: could not read Username for 'https://github.com': termina
l prompts disabled
        Confirm the import path was entered correctly.
        If this is a private repository, see https://golang.org/doc/faq#git_http
s for additional information.
