### ISSUE TITLE
typo: PEADME.md to README.md

### ISSUE THREAD

**Issue by yakushou730** [bigwhite/GoProgrammingFromBeginnerToMaster#4]
GO語言精進之路-從新手到高手的編程思想、方法和技巧 1 的

第 36 頁
5-2 小節的附圖
![typo-pic](https://user-images.githubusercontent.com/17252776/161439480-c627ad85-c2ca-45d6-960d-0c787b175252.jpg)

**Comment by bigwhite** [comment]
火眼金睛啊。感谢指出！
