### ISSUE TITLE
37.5下面的“小结”好像有问题

### ISSUE THREAD

**Issue by AVOlili** [bigwhite/GoProgrammingFromBeginnerToMaster#5]
微信阅读上看的，页数不清楚,第七部分 第37条的小结
原文：
如果可以通过错误值类型的特征进行错误检视，那么尽量使用错误行为特征检视策略；在上述两种策略无法实施的情况下，再用“哨兵”策略和错误值类型检视策略；

感觉应该是: 
如果可以通过错误值类型的特征进行错误检视，那么尽量使用错误值类型特征检视策略；在上述两种策略无法实施的情况下，再用“哨兵”策略和错误行为特征检视策略；

**Comment by bigwhite** [comment]
的确存在表达模糊，前后不一致的情况。我后续列到勘误中，感谢指出。
