### ISSUE TITLE
代码异议

### ISSUE THREAD

**Issue by Callmexiaowu8** [bigwhite/GoProgrammingFromBeginnerToMaster#9]
书名：Go语言精进之路vol1
版次：2022年1月第1版第1次印刷
位置：p103
内容：
![image](https://user-images.githubusercontent.com/103716382/165942160-de592548-e632-4e21-b035-344df60c8a1f.png)
这样并不是在获取元素的地址，是否应该改为
```go
p := &m[key] //无法获取m[key]的地址
fmt.Println(p)
```

**Comment by bigwhite** [comment]
已加入勘误，感谢指出。

**Comment by Callmexiaowu8** [comment]
谢谢作者，第一册大致读了一遍，对我来说这是一本值得买、买了不后悔的书 。 👍
